name: "Deploy Codigo Facilito"

on: push
 branches: ["Main"]

 jobs:

 deploy-codigofacilito:
  runs-on: ubuntu-latest
  steps:
    use: actions/checkout@v4
    run: echo "Hacemos pull del codigo"
    run: echo "Correr migraciones"
    run: echo "generar binarios"