name: "Deploy Codigo Facilito"

on:
  push:
    branches:
      - "operaciones-extra"

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binarios"
